### ISSUE TITLE
incompatible with Angular 6 and rxjs 6

### ISSUE THREAD

**Issue by jasefisher** [HackAfro/angular-epic-spinners#1]
When trying to use this excellent library after upgrading to Angular 6 and rxjs 6, it no longer compiles.

Angular 6.0.3
rxjs 6.2.0

Error:
Failed to compile.

ERROR in node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.
node_modules/angular-epic-spinners/node_modules/@angular/core/src/application_ref.d.ts(8,10): error TS2305: Module '"c:/node/satng/node_modules/rxjs/Observable"' has no exported member 'Observable'.
node_modules/angular-epic-spinners/node_modules/@angular/core/src/event_emitter.d.ts(8,10): error TS2305: Module '"c:/node/satng/node_modules/rxjs/Subject"' has no exported member 'Subject'.
node_modules/angular-epic-spinners/node_modules/@angular/core/src/linker/query_list.d.ts(8,10): error TS2305: Module '"c:/node/satng/node_modules/rxjs/Observable"' has no exported member 'Observable'.
node_modules/angular-epic-spinners/node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.
node_modules/angular-epic-spinners/node_modules/@angular/core/src/util/lang.d.ts(8,10): error TS2305: Module '"c:/node/satng/node_modules/rxjs/Observable"' has no exported member 'Observable'.
node_modules/rxjs/Observable.d.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/Observable'.
node_modules/rxjs/Subject.d.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/Subject'.

**Comment by HackAfro** [comment]
Apologies @jasefisher, I’m currently working on making it compatible with Angular 6

**Comment by jasefisher** [comment]
Great, thank you!

**Comment by HackAfro** [comment]
Hello, @jasefisher. I've published a new version of the library that supports angular 6. Apologies for the delay

**Comment by jasefisher** [comment]
Works like a charm now, thank you!

**Comment by wamburu** [comment]
Am facing the same issue when using angular v6
![screen shot 2018-06-26 at 13 12 50](https://user-images.githubusercontent.com/6532631/41905078-c0df3dcc-7942-11e8-90b2-1b943ee40074.png)
Any work around on this?
Reagards

**Comment by wamburu** [comment]
I downgraded to  v1.0.3 and it works right 💯
